"use strict";
console.log("AppCodename",navigator.appCodeName,'\n')
console.log("appName",navigator.appName,'\n')
console.log("appVersion",navigator.appVersion,'\n')
console.log("connection",navigator.connection,'\n')
console.log("geolocation",navigator.geolocation,'\n')
console.log("language",navigator.language,'\n')
console.log("languages",navigator.languages,'\n')
console.log("mimeTypes",navigator.mimeTypes,'\n')
console.log("onLine",navigator.onLine,'\n')
console.log("UserAgent",navigator.userAgent,'\n')
console.log("cookieEnabled",navigator.cookieEnabled,'\n')
console.log("clipboard",navigator.clipboard,'\n')
console.log("connection",navigator.connection,'\n')
console.log("serviceWorker",navigator.serviceWorker,'\n')
console.log("plugins",navigator.plugins,'\n')